### ISSUE TITLE
Duplicate entries in bibliography and footnotes

### ISSUE THREAD

**Issue by Sieboldianus** [shyamd/mkdocs-bibtex#110]
I am not sure what is causing this, but I updated to the latest mkdocs-bibtex and I am seeing duplicate entries of references. Have a look here:
[lbsn.vgiscience.org mkdocs material docs](https://lbsn.vgiscience.org/structure/metrics/)

If the same citation is references several times, it will appear the same number of times duplicates in the bibliography.

<details><summary>Here's our mkdocs.yml:</summary>

```yml
site_name: LBSN Structure
site_url: https://lbsn.vgiscience.org/
site_author: Alexander Dunkel, Marc Löchner, Filip Krumpe
copyright: CC BY 4.0, 2022 Alexander Dunkel, Marc Löchner, Filip Krumpe, vgiscience.org and contributors
site_dir: site

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
  - bibtex:
      bib_file: 'docs/references.bib'
      csl_file: 'apa.csl'

theme:
    name: 'material'
    custom_dir: overrides/
    palette:
      primary: 'Light Blue' #43C3F5
      accent: 'Orange' #F8A610
    logo: 'img/logo-white.svg'
    favicon: 'img/favicon.png'
    features:
      - navigation.instant
      - navigation.expand
      - navigation.top

...

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - tables
  - sane_lists
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
```
</details>

Here is some more testing:
- also happens with default `csl_file` (parameter set to none)
- mkdocs `1.2.3` and mkdocs-material `8.2.5` (both latest), mkdocs-bibtex `2.0.2`
- also happens with the test files provided in this repository
- as you can see in the exmaple docs above, there are `:::` characters added beyond each bibliography ending. This is independent of the csl file uses. I don't know where these are coming from.
- I have a feeling that this may be related to pandoc, or the way it is installed, or the version. Running `pandoc 2.17.1.1` locally, installed with conda, 
- in Debian Docker I observe the same behavior (same pandoc version, but installed with *.deb)
