### ISSUE TITLE
mkdocs-bibtex does not render citations where a period (.) exists in the key

### ISSUE THREAD

**Issue by NixImagery** [shyamd/mkdocs-bibtex#170]
When rendering a site with mkdocs using the mkdocs-bibtex plugin, citations are not recognised if they have a period within the citation key.

I tried a minimum working example and could reproduce the behaviour. To reproduce the behaviour, set up a folder containing the files below and run the command `mkdocs serve`. The browser should render both citations correctly but it only functions as expected for the citation key without the period.

## MWE

Site structure:

- MWE
  - docs
    - index.md
  - mkdocs.yml
  - mwe.bib

### index.md

```markdown
# Home

Blah blah [@Jarse2023]. 

Woof woof [@Jarse.2023]
```

### mkdocs.yml

```yaml
site_name: MWE
docs_dir: docs
site_dir: site

plugins: 
  - search
  - bibtex:
      bib_file: mwe.bib

markdown_extensions:
  - footnotes

```

### mwe.bib

```bibtex
@article{Jarse2023,
author = {Jarse, Hugh},
journal = {Beano},
title = {{The width of seats on urban public transport}},
year = {2023}
}
@article{Jarse.2023,
author = {Jarse, Hugh},
journal = {Beano},
title = {{The width of seats on urban public transport}},
year = {2023}
}

```
