### ISSUE TITLE
Add an option for loading an api key

### ISSUE THREAD

**Issue by griff-rees** [shyamd/mkdocs-bibtex#171]
The flexibility of a URL is great, but they'd prefer API keys were in the header: https://www.zotero.org/support/dev/web_api/v3/basics

Any chance an option following their API and `mkdocs` [environmental variable options](https://www.mkdocs.org/user-guide/configuration/#environment-variables) could be added, something like:

```yaml
- bibtex:
    bib_file:
      zenodo: true
      zenodo_user_or_goup_id: !ENV [A_SYSTEM_VAR, ZENODO_GROUP, "1234567"]  # Zenodo group ID number
      zenodo_api_key: !ENV [ANOTHER_SYSTEM_VAR, A_GITHUB_ENV, ZENODO_API_KEY]
```

to fill in this sort of template:

```
https://api.zotero.org/groups/${zenodo_user_or_group_id}/items?format=bibtex&key=${zenodo_api_key}
```

A slicker option could use [`pyyaml-env`](https://pypi.org/project/pyaml-env/) or [`python-dotenv`](https://github.com/theskumar/python-dotenv) to use a local `.env` like:

```dotenv
ZENODO_GROUP=1234567
ZENODO_API_KEY=12345671234567
```

but that might be a feature request for `mkdocs` generally. That was mentioned in [this ticket](https://github.com/mkdocs/mkdocs/issues/1954#issuecomment-582487448) but as best I understand only environmental variables were added via [`pyyaml-env-tag`](https://github.com/waylan/pyyaml-env-tag) (hence the documentation linked above which follows the same format).
