### ISSUE TITLE
Default footnotes ignore/overwrite existing footnotes

### ISSUE THREAD

**Issue by daylinmorgan** [shyamd/mkdocs-bibtex#173]
I sometimes use a simple numbering scheme with footnotes i.e. `[^1][^2]`. 

If a document already uses footnotes then the plugin will happily override them.

A simple solution may be to namespace the footnotes to make this less likely and add this info to the README.

For example
```markdown 
[^1-citation]: ....

[^ref1]: .....
```

Or perhaps exposing this a user configurable option and defaulting to the existing behavior.

```yaml
plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
      footnote_format: "ref{number}"
markdown_extensions:
  - footnotes
```

I can submit a PR if this makes sense.
