### ISSUE TITLE
bibtex makes the normal link in mkdocs not working.

### ISSUE THREAD

**Issue by leiwu84** [shyamd/mkdocs-bibtex#289]
I have made a simple example.

The repo directory tree is:

```
├── docs
│   ├── index.md
│   └── refs.bib
├── mkdocs.yml
```

The `mkdocs.yml` file is:
```yaml
site_name: My site
docs_dir: docs

theme:
  name: material

nav:
  - Home: index.md

plugins:
  - autorefs
  - search
  - bibtex:
      bib_file: 'docs/refs.bib'
```

The file content of `index.md` contains a normal link: `[displaying text](url)`.

```
This is [google](www.google.com).
```

If I use `mkdocs-bibtex==2.14.5`, the link. of `google` is rendered correctly.

<img width="521" alt="Image" src="https://github.com/user-attachments/assets/9e1d48c6-ad45-4e01-8bcc-8c469eea9694" />

But if I use `mkdocs-bibtex==3.0.0`, the link. of `google` is rendered incorrectly.

<img width="530" alt="Image" src="https://github.com/user-attachments/assets/5f63851e-7666-4488-ae52-8b436a28ec6d" />

Can you please help with this? Thanks!
