### ISSUE TITLE
Trying to use it with tox to build docs with refs - but no effect

### ISSUE THREAD

**Issue by cwerner** [shyamd/mkdocs-bibtex#38]
Hi.

I just found your tool - looks great! However, when I try to build my MkDocs with tox I do not get any citations at all? Neither any errors...

This is the tox section:
```
[testenv:docs]
description = Run a development server for working on documentation
basepython = python3.7
deps = mkdocs
       mkdocs-bibtex
       mkdocs-material
       pymdown-extensions
```

And in my index.md I use it like so:
```
Some content [@MrScience:2011].

\bibliography
``` 

This is the relevant section in MkDocs.yml:
```
plugins:
    - search
    - bibtex:
        bib_file: "docs/selpapers.bib"
        cite_style: "pandoc"
```

**Result:**

I have the citation as-is in my document (als plain text) and no bibliography at the end...

Do I miss something here?

Cheers,
C
